[phases.build]
cmds = [
    "composer install --no-dev --optimize-autoloader"
]

[phases.deploy]
cmds = [
    "php bin/create-schema.php",
    "php bin/create-admin-user.php", 
    "php bin/load-fixtures.php"
]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public"